language: java

jdk:

  - oraclejdk7

  - openjdk7

  

before_install:

 - pwd
 - ls
 - chmod +x gradlew
 - git clone https://github.com/LosIsotopos/jrpg-2017a-dominio.git ~/build/LosIsotopos/jrpg-2017a-dominio

